import type { Answer, SolveRequest } from '../contract';
import { normalizeClue } from '../clue-norm';

export const NAME = 'Clue bank';

/**
 * Normalized clue → the answers it has been published with, most frequent
 * first. Generated by `npm run build:cluebank`; see that script and
 * docs/CLUEBANK.md for where the source data comes from.
 */
export type ClueBank = Record<string, string[]>;

/**
 * Loaded on first use rather than bundled into the entry chunk. The bank is
 * the largest thing the app ships and most of a session never touches it, so
 * Vite splits it into its own chunk; the service worker precaches that chunk,
 * which keeps the lookup offline without paying for it on first paint.
 */
let bank: ClueBank | null = null;
let loading: Promise<ClueBank> | null = null;

export function loadClueBank(): Promise<ClueBank> {
  if (bank) return Promise.resolve(bank);
  loading ??= import('../data/cluebank.json')
    .then((m) => (bank = (m.default ?? m) as ClueBank))
    .catch(() => (bank = {}));
  return loading;
}

/** For tests: inject a bank without touching the generated file. */
export function setClueBank(next: ClueBank): void {
  bank = next;
  loading = Promise.resolve(next);
}

/**
 * Exact clue lookup, and only exact.
 *
 * Every entry here is a clue that a published puzzle actually used with this
 * answer, which is the strongest evidence the app has — far stronger than
 * semantic nearness — so hits are marked with a priority that lifts them
 * above everything Datamuse returns. That strength is exactly why the match
 * has to stay exact: relaxing it would trade the one thing that makes the
 * bank worth ranking first.
 *
 * Order within a clue is preserved from the bank (most frequently published
 * answer first) by stepping the score down slightly for each one.
 */
export function lookupClue(bank: ClueBank, req: SolveRequest): Answer[] {
  const key = normalizeClue(req.query);
  const answers = key ? bank[key] : undefined;
  if (!answers?.length) return [];
  return answers.map((answer, i) => ({
    answer,
    display: answer.toLowerCase(),
    length: answer.length,
    score: Math.max(0.9, 1 - i * 0.02),
    priority: 1,
    fitsPattern: null,
    source: 'cluebank' as const,
  }));
}

/** Convenience wrapper: load the bank if needed, then look the clue up. */
export async function findPublished(req: SolveRequest): Promise<Answer[]> {
  return lookupClue(await loadClueBank(), req);
}
